server:
  port: 8080
  servlet:
    context-path: /zilla
    encoding:
      charset: UTF-8

logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

app:
  api:
    prefix: /v1
  aes:
    key: 
    key-book: 
    key-book-length: 
  token:
    access: 
    refresh: 
  admin:
    id: 
    password: 
  target:
    ip: 
    port: 
    username: 
    password: 
    server-directory: 
    protocol:
  compare:
    suffix: 
  log:
    base-dir: logs
    connection-dir: connections
    connection-file: connection